# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823344bfdff9ca2439c38a0f8e4cac7f7b5e27cd07cc8904980182d7dfce2c0f9eb25949f99b4349a23ceecb43f4a9d2325badc1f406aa49d943d37386b79679

test:
  secret_key_base: 49ee755debd3905dfe173d52cecb41a27bbe052c132be324bfb34eaa7a0e1aae7060057120d120f8e763814af7897ffac5d399ea11dca3269bc112cee4a2eb55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
